services:
  hybridhub-redis:
    container_name: pharmago-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: seunggison/pharmago-redis
    ports:
      - "6379:6379"
  hybridhub-database:
    container_name: pharmago-database
    build:
      dockerfile: Dockerfile
      context: ./db
    image: seunggison/pharmago-database
    environment:
      - MARIADB_DATABASE=pharmago
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./db/config:/etc/mysql/conf.d
    ports:
      - "3306:3306"