spring:
  profiles:
    active: prod
    group:
      local:
        - common
      prod:
        - common

server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: common

kakao:
  rest-api-key: ${KAKAO_REST_API_KEY}

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/pharmago
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

base:
  url: http://localhost:8081/find/

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://pharmago-database:3306/pharmago
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    redis:
      host: pharmago-redis
      port: 6379
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

base:
  url: http://43.202.247.102/find/